name: MWAA Dags Deploy
on:
  push:
    paths:
    - "images/airflow/3.0.6/dags/**"
    branches:
    - master
  
  workflow_dispatch: # allows manual trigger of actions if needed

env:
  BUCKET_NAME: "tovala-airflow-prod"
  AWS_REGION: "us-east-1"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@main
      
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::307553795271:role/line_cook_github_actions
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Sync dags to S3
        run: |
          aws s3 sync ./images/airflow/3.0.6/dags s3://${{ env.BUCKET_NAME }}/dags --follow-symlinks --delete --exclude "spice_rack/*"
